### ISSUE TITLE
Explicitly set CPU affinity?

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/rustc-perf-collector#12]
I wonder if we could benefit a bit from setting the CPU affinity to ensure that we're locked on one core, and maybe also raise the priority of the process to ensure we're the *only* process running on that core?

**Comment by Mark-Simulacrum** [comment]
I currently run the benchmarks with a nice value of -20 (documented as most favorable to the process) and the machine which runs benchmarks currently has just one CPU, so setting CPU affinity should have no effect. I'm uncertain whether adding an additional core and then restricting to just one CPU would have an effect, though. Always open to experimentation!

I'm not sure, but I think setting the niceness didn't have an effect on the priority of the process (which appear to be different things). I'm not sure how to set the priority at start.

**Comment by alexcrichton** [comment]
Closing as I think we definitely don't want to do this.
